### ISSUE TITLE
Disagreements on Transactions and Balances with Dash Wallet (Testnet)

### ISSUE THREAD

**Issue by HashEngineering** [akhavr/electrum-dash#145] opened 2020-10-08 04:32 UTC
Problem:
After taking a BIP39 recovery phrase (mnemonic seed) from the Dash Wallet app for android that runs on the testnet network and importing it into Dash Electrum Testnet, the balances and transaction amounts do not match.

Transaction amounts don't match because the most recent transactions may not be accounted for correctly in terms of the change that is involved.  That is in the last screenshot, where a -0.2 Dash transaction appears as a -1.00 dash transaction.   Earlier transactions in the wallet appear to account for change correctly.  This may explain the reason why the balances do not match, though there could be other reasons like missing or extra transactions.  Some mixing was done after the app was loaded into Dash Electrum Testnet for private send using v3.3.8.3 in May 2020.

BIP39 mnemonic seed:  `angry crowd reject crush field boy occur dish balcony pistol awful elegant`
Wallet dump file from the Test Net App:  This details all keys and paths involved.
https://drive.google.com/file/d/1f8XHsM78SuJfotw4NvbuhpBeBuFEZDgE/view?usp=sharing

Dash Wallet 7.0.8 (testnet app): https://github.com/dashevo/dash-wallet/releases/download/v7.0.8/dash-wallet-7.0.8-testnet.apk

![electrum-tx-list](https://user-images.githubusercontent.com/5956129/95414202-26b59e80-08e2-11eb-91a0-85db0d773e1c.png)
![app-tx-list1](https://user-images.githubusercontent.com/5956129/95414197-261d0800-08e2-11eb-92c8-9da267cdaeb7.jpg)
![app-tx-list2](https://user-images.githubusercontent.com/5956129/95414198-26b59e80-08e2-11eb-8ec4-073ffb5efef3.jpg)
![single-tx](https://user-images.githubusercontent.com/5956129/95414200-26b59e80-08e2-11eb-9dd2-f9f5ec670354.png)

**Comment by zebra-lucky** [comment] 2020-10-08 11:16
Try to set more high `gap_limit`, `gap_limit_for_change`.

Seems on this seed there is addresses with big gap.

In console tab try to run:
```
wallet.gap_limit_for_change = 100
```

https://electrum.readthedocs.io/en/latest/faq.html#what-is-the-gap-limit

**Comment by akhavr** [comment] 2020-10-08 11:48
Not closing yet, since we still can't reproduce some utxo classification in your example.

**Comment by HashEngineering** [comment] 2020-10-09 20:51
It is true that the Dash Wallet app for Android does use a gap of 100.

**Comment by akhavr** [comment] 2021-02-09 10:57
Looks like this is solved.  Please reopen with more details if this is still an issue.

**Closed by akhavr** 2021-02-09 10:57 UTC
