### ISSUE TITLE
Ledger Nano S not properly recognized, not possible to confirm transaction

### ISSUE THREAD

**Issue by jamiemirror** [akhavr/electrum-dash#50] opened 2018-09-27 18:43 UTC
Hi,
my Ledger Nano S wallet was recognized as generic Ledger only. 
The basic access, using DASH application on the wallet and Electrum 3.2.2.1 was fine, but when I decided to send some dash, Electrum application stuck on confirmation pop-up, waiting the Ledger wallet to confirm transaction. However no notification was shown on Ledger display, hence no transaction can be made.

Best regards

**Comment by akhavr** [comment] 2018-10-06 09:06
Ok, problem confirmed.  We're working to fix this.

**Comment by PanderMusubi** [comment] 2020-03-20 07:12
What is the progress?

**Comment by akhavr** [comment] 2020-03-23 15:42
Should be fixed now.  At least, it works for me.  Reopen with more details, if it fails for you.

**Closed by akhavr** 2020-03-23 15:42 UTC
